[browser]
gatherUsageStats = false

[theme]
base                    = "dark"
primaryColor            = "#1E90FF"
backgroundColor         = "#0F1117"
secondaryBackgroundColor = "#1A1D27"
textColor               = "#E0E0E0"
font                    = "sans serif"
