[browser]
gatherUsageStats = false

[theme]
base                    = "dark"
primaryColor            = "#2BD9C4"
backgroundColor         = "#0C0B09"
secondaryBackgroundColor = "#15120D"
textColor               = "#F4EBDD"
font                    = "monospace"
